version: "3.7"
services:
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_management_system
    volumes:
      - db_data:/var/lib/mysql
  server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  db_data:
